### ISSUE TITLE
Running ethernet_bridge crashes

### ISSUE THREAD

**Issue by HuErr** [ntkernelcom/ndisapi#1]
I confirm that running ethernet_bridge crashes after installing virtnet。

	// Before Windows 10 NDISWANIP can be identified bt internal name
	//
	if (!ms_Version.IsWindows10OrGreater() /*before Windows 10*/)
	{
		if (_stricmp(adapterName, DEVICE_NDISWANIP) == 0)
		{
			return TRUE;
		}
	}

**Comment by HuErr** [comment]
GetTcpipBoundAdaptersInfo renturn false

**Comment by ntkernelcom** [comment]
> GetTcpipBoundAdaptersInfo renturn false

Normally it means that you have not installed Windows Packet Filter driver or it was disabled or prevented from loading (by security policy an example).

Driver installers can be downloaded from the link below:

https://www.ntkernel.com/windows-packet-filter/

However, if the driver is installed then could you please provide more detailed information.

**Comment by HuErr** [comment]
system: Windows 10 family Chinese version
type : 64bits
I installed the windows-packet-filter driver, causing the system to be out of the network.

**Comment by ntkernelcom** [comment]
It looks like driver signing policy issue. Windows 10 Enterprise?

**Comment by ntkernelcom** [comment]
Driver signatures were updated. All known problems with installing driver should have gone.
