### ISSUE TITLE
[v3.2.29.1] Driver digital signature issue.

### ISSUE THREAD

**Issue by an-eternity** [ntkernelcom/ndisapi#12]
The driver of this version can not work properly because of some issue related to a digital signature.
On some machines right when the driver installation process is completed a popup dialog appears that warns about the failed driver that has no digital signature.
On another machines no such popup dialogs appear, but the driver doesn't work anyway, and when user tries to start the driver manually via the Device Manager, an attempt to start it is failed with a message that digital signature for the file can not be verified (screenshot of this message is in attachment).
When the driver v3.2.29.1 is uninstalled and previous version (v3.2.28.1) is installed back, the driver begins to work right away, even without OS restart.

This issue is related to the driver for 64-bit systems (tested on several machines with Windows 7 and 8).
Driver for 32-bit systems has not been tested yet.
Driver for legacy systems is working properly.

![WinpkFilter_3-2-29-1_Ndisrd-Issue](https://user-images.githubusercontent.com/72374425/116259158-3b725a80-a77e-11eb-8a08-22d08e864502.png)

**Comment by an-eternity** [comment]
We have tested several more machines now with version v3.2.29.1 for 64-bit... This problem doesn't happen not in one of them that use Windows 10.

**Comment by ntkernelcom** [comment]
Thanks for pointing this. By mistake Windows 7/8 drivers were signed with test certificate. I have updated the installers.

**Comment by an-eternity** [comment]
Now i can confirm, drivers from the updated installer for 64-bit platforms work properly on all tested machines. The issue is fixed.
