### ISSUE TITLE
Visual Studio 2017 and Win 10 SDK 10.0.17763.0 can't build ndisapi.dll, ndisapi.lib and ndisapi.net

### ISSUE THREAD

**Issue by frankzha** [ntkernelcom/ndisapi#2]
1. when i tried to build those 3 projects, it gave the error like below ( i specified the build output to be verbose): (I am using vs community 2017, build 15.9.4)

1>------ Up-To-Date check: Project: ndisapi.dll, Configuration: Debug x64 ------
1>Project is not up-to-date: last build was unsuccessful.
1>------ Build started: Project: ndisapi.dll, Configuration: Debug x64 ------
1>Object reference not set to an instance of an object.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by ntkernelcom** [comment]
Most of the projects were configured for the earlier version of SDK (16299, which you probably had not installed), so to fix this you only had to change the SDK version in the project settings. Anyway, to simplify the things I've updated SDK version to 10.0.17763.0, just make a pull.

**Comment by frankzha** [comment]
Which version of visual studio are you using? I am using VS 2017 community.
I got the latest code and still had the same error. I wonder if it's due to I am using community version.

**Comment by ntkernelcom** [comment]
Visual Studio 2017 Community works just fine, however that depends on what components you have installed. Besides main Workloads: ".NET desktop development" and "Desktop development with C++" note to add Optionals: "Visual C++ MFC for x86 and x64" and "C++/CLI support".  It should fix the issues.

**Comment by frankzha** [comment]
Finally after i upgraded visual studio community 15.9.4 to latest 15.9.7 and it started to work. Thank you very much!

BTW, the linker for ebridge is not a valid path:
$(SolutionDir)\..\ndisapi\bin\lib\$(Platform)\$(Configuration)\ 

It should be: 
$(SolutionDir)\bin\lib\$(Platform)\$(Configuration)\

**Comment by ntkernelcom** [comment]
Thank for clue! Original project layout was a little bit different.
