### ISSUE TITLE
API question

### ISSUE THREAD

**Issue by mehecip** [ntkernelcom/ndisapi#9]
Hi,

this is not an issue per say, more of a question.

If after calling: 

`BOOL CNdisApi::SendPacketsToMstcpUnsorted ( PINTERMEDIATE_BUFFER* Packets, DWORD dwPacketsNum, PDWORD pdwPacketsSuccess );`

`dwPacketsNum` would be different than `pdwPacketsSuccess`, what could be the causes for the "dropped" packets?

https://github.com/ntkernelcom/ndisapi/blob/c20f80194b0425e4761d0b0847e0bfef781dacb5/examples/cpp/common/ndisapi/fastio_packet_filter.h#L479

Thanks.

PS: I'm a big fan of the API and examples.

**Comment by ntkernelcom** [comment]
Hi,

These packets will be silently dropped. However, the chance for this is minimal. IIt may happen if:write_adapter_request is formed properly

**Comment by ntkernelcom** [comment]
Hi,

These packets will be silently dropped. However, the chance for this is minimal. It may happen if:

- write_adapter_request is malformed
- corresponding network adapter was removed from the system
- system does not have have enough resources to allocate the packet

Regards,
Vadim

**Comment by mehecip** [comment]
Thanks for the quick answer.
